context:
  name: aiida-fans
  version: "0.1.4"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name | replace("-", "_") }}/${{ name | replace("-", "_") }}-${{ version }}.tar.gz
  sha256: 28415a9ba4338ba4088d239600ad81c2d0c78e85b72cfec14f7814749fee14c4

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=64.0.0
    - setuptools-scm >=8.0.0
  run:
    - python >=${{ python_min }}
    - aiida-core >=2.3.0

tests:
  - python:
      imports:
      - aiida_fans
      pip_check: true
      python_version: ${{ python_min }}.*
  - if: osx or linux
    then:
    - script:
        - verdi plugin list aiida.calculations fans
      requirements:
        run:
          - python ${{ python_min }}.*

about:
  homepage: https://github.com/ethan-shanahan/aiida-fans
  summary: 'AiiDA plugin for FANS, an FFT-based homogenization solver.'
  description: |
    This is a plugin for AiiDA that facilitates the use of FANS. FANS is an FFT-based homogenisation solver for microscale and multiphysics problems. It is an open-source project under active development at the Institute of Applied Mechanics, University of Stuttgart. This plugin aims to bring the full value of provenance tracking and database integration to the results produced by FANS.
  license: LGPL-3.0-only
  license_file: LICENSE
  documentation: https://aiida-fans.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - claudiushaag
