context:
  name: aiida-fans
  version: "0.2.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name | replace("-", "_") }}/${{ name | replace("-", "_") }}-${{ version }}.tar.gz
  sha256: 225a5a106c0cee2249edd3d61815bedfa763a0dbf8421716bb5dd6b4283e9628

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0
  python:
    entry_points:
      - fans = aiida_fans.data:FANSParameters
      - fans = aiida_fans.calculations:FANSCalculation
      - fans = aiida_fans.parsers:FANSParser
      - fans = aiida_fans.cli:data_cli

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=64.0.0
    - setuptools-scm >=8.0.0
  run:
    - python >=${{ python_min }}
    - aiida-core >=2.6.0
    - h5py

tests:
  - python:
      imports:
        - aiida_fans
      pip_check: true
      python_version: ${{ python_min }}.*
  - if: osx or linux
    then:
      - script:
          - verdi plugin list aiida.calculations fans
          - verdi plugin list aiida.parsers fans
        requirements:
          run:
            - python ${{ python_min }}.*

about:
  homepage: https://github.com/DataAnalyticsEngineering/AiiDA-FANS
  summary: 'AiiDA plugin for FANS, an FFT-based homogenization solver.'
  description: |
    This is a plugin for AiiDA that facilitates the use of FANS. FANS is an FFT-based homogenisation solver for microscale and multiphysics problems. It is an open-source project under active development at the Institute of Applied Mechanics, University of Stuttgart. This plugin aims to bring the full value of provenance tracking and database integration to the results produced by FANS.
  license: LGPL-3.0-only
  license_file: LICENSE
  documentation: https://aiida-fans.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - ethan-shanahan
    - EMMAOpenSource
    - sanathkeshav
    - claudiushaag
